#!/bin/bash

set -e

# This is a destructive operation and should not run in staging or production.
if [ "${ENV}" != "dev" ]
then
  echo "Environment not set to 'dev'."
  exit 1
fi

. account_settings "$@"

TERRAFORM_DIR="/usr/local/src/terraform"
pushd "${TERRAFORM_DIR}"

terraform init \
  -backend-config=vars/backend-"${ENV}".tfvars

. select_workspace "$@"

WORKSPACE=$(terraform workspace show)

# We can't delete the default workspace.
# If you want to delete all infrastructure form the default branch
# You will have to run terraform destroy manually
if [ "$WORKSPACE" == "default" ]
then
  echo "Can't delete default workspace."
  exit 1
fi

terraform destroy \
        -var-file="vars/terraform-${ENV}.tfvars" \
        -auto-approve
terraform workspace select default
terraform workspace delete "${WORKSPACE}"




