#!/bin/bash

function usage {
  echo -n \
    "Usage: $(basename "$0") COMMAND OPTION[S]
Execute Terraform subcommands.
"
}

set -e

. settings "$@"


# Run Terraform
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  if [ "${1:-}" = "--help" ]; then
    usage
  else
    case "${1}" in
    fmt)
      terraform fmt -recursive .
      ;;
    init)
      echo "Initializing terraform ..."
      shift
      # Clear stale modules, then re-initialize
      rm -rf .terraform
      terraform init \
        -backend-config=vars/backend-"${ENV}".tfvars
      . select_workspace "${WORKSPACE}"
      ;;
    doc)
      echo "Starting terraform documentation..."
      shift
      # Clear stale modules, then re-initialize
      rm -rf .terraform
      # select or create the current workspace
      echo "Terraform documentation - Running pre-doc init"
      terraform init \
        -backend-config=vars/backend-"${ENV}".tfvars
      . select_workspace "${WORKSPACE}"
      echo "Terraform documentation - Running terraform-docs"
      terraform-docs markdown table . > ../terraform.md
      ;;
    plan)
      echo "Starting terraform plan..."
      shift
      # Clear stale modules, then re-initialize
      rm -rf .terraform
      # select or create the current workspace
      echo "Terraform plan - Running pre-plan init"
      terraform init \
        -backend-config=vars/backend-"${ENV}".tfvars
      . select_workspace "${WORKSPACE}"
      echo "Terraform plan - Running plan"
      terraform plan \
        -var-file="vars/terraform-${ENV}.tfvars" \
        -out="terraform.tfplan" \
        "$@"
      echo "Terraform plan finished."
      ;;
    apply)
      shift
      echo "Starting terraform apply..."
      terraform apply \
        "terraform.tfplan"
      echo "Terraform apply finished."
      ;;
    force-unlock)
      terraform force-unlock -force "${LOCK_ID}"
      ;;
    destroy)
      shift
      echo "Starting terraform destroy..."
      . select_workspace "${WORKSPACE}"
      terraform destroy \
        -var-file="vars/terraform-${ENV}.tfvars" \
        -auto-approve \
        "$@"
      echo "Terraform destroy finished."
      ;;
    *)
      echo "ERROR: I don't have support for that Terraform subcommand!"
      exit 1
      ;;
    esac

#    popd
  fi
fi
